### ISSUE TITLE
Tracking ticket for re-enabling updated Genome Space importer/exporter tools at main

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#100]
**Note for users working at Galaxy Main https://usegalaxy.org** A ~~minor~~ medium security issue was found and the tools are undergoing a correction. They are currently disabled and prior data outputs were modified server-side. 

We will update this ticket once the functionality is re-enabled and tested.

ping @natefoo @davebx @blankenberg

**Comment by martenson** [comment]
This has been fixed by downgrading the tool back to supporting only openID. It can be re-enabled on Main.

**Comment by natefoo** [comment]
The GenomeSpace tools are now reenabled on Test/Main.

**Comment by jennaj** [comment]
Testing.

**Comment by jennaj** [comment]
The exporter is failing at the step where a directory is selected at GS through their pop-up window. Seems very slow to load (5-8 minutes) then when a target dir is selected, nothing happens. If "close" is clicked on (thinking the dir was selected), nothing is populated back into the Galaxy tool form.

The GS pop-up is labeled with "beta" so not sure if our problem or not, but this should work if enabled, yes?

Testing import next.

**Comment by jennaj** [comment]
Importer stalls, too and the text formatting is odd. Looks like they are still working on it and maybe isn't functional right now. I created a fresh link right before for this test, so the open id token being stale shouldn't be a factor.

If this is ok, we can close this out again. This doesn't seem to be a problem we can fix on our end. Or has anyone else had more success?

This graphic is from using the IMPORTER tool, even though states "Saving file to GenomeSpace" 
<img width="520" alt="screen shot 2018-03-15 at 4 57 52 pm" src="https://user-images.githubusercontent.com/8999735/37496911-7c52e68e-2872-11e8-87ab-044efffcd87b.png">

**Comment by nuwang** [comment]
@natefoo It looks like a dependency issue. I think a downgrade to "python-genomespaceclient<1.0.0" should fix it. Some properties were renamed in 1.0.0 (e.g. dataFormat became data_format).

**Comment by jennaj** [comment]
@natefoo The exporter works for me now, too. The Importer still errors. 

Test history, see last two datasets https://usegalaxy.org/u/jen/h/test-history-genomespace-importer-exporter

**Comment by jennaj** [comment]
ping @martenson @natefoo  @davebx 

The GS importer is failing with some datatypes and success for others. Related to yesterday's main update or is the GS connection failing in some inconsistent way? Is the same "list" error that some other "get data" tools are producing, but for different datatypes. (ex: UCSC ends with metadata warning for BED, fasta, gtf -- only actually fails with tabular data).

Tested in the same history and sent in a bug report. https://usegalaxy.org/u/jen/h/test-history-genomespace-importer-exporter

Was able to export a bed (data 1) and immediately import back (data 16) with no error. A random bed file from a public GS lib also imported Ok. 

Error below when importing a gtf file (data 13). similar error for fastq (data 14) and bam (data 15). 

```
Job Traceback
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 690, in finish_job
    self._finish_or_resubmit_job(job_state, stdout, stderr, exit_code)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 433, in _finish_or_resubmit_job
    job_state.job_wrapper.finish(stdout, stderr, exit_code, check_output_detected_state=check_output_detected_state)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 1288, in finish
    dataset.init_meta(copy_from=dataset)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 2202, in init_meta
    return self.datatype.init_meta(self, copy_from=copy_from)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 2132, in datatype
    return datatype_for_extension(self.extension)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 2042, in datatype_for_extension
    ret = datatypes_registry.get_datatype_by_extension(extension)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/registry.py", line 565, in get_datatype_by_extension
    return self.datatypes_by_extension.get(ext, None)
TypeError: unhashable type: 'list'
```

**Comment by martenson** [comment]
@jennaj this will be fixed by https://github.com/galaxyproject/galaxy/pull/6196

**Comment by jennaj** [comment]
Saw that, thanks. I'm linking tickets together so can find these and test quickly once on main.

UCSC https://github.com/galaxyproject/usegalaxy-playbook/issues/119
GenomeSpace https://github.com/galaxyproject/usegalaxy-playbook/issues/100
EBI SRA https://github.com/galaxyproject/usegalaxy-playbook/issues/117
