### ISSUE TITLE
update cummerbund

### ISSUE THREAD

**Issue by martenson** [galaxyproject/usegalaxy-playbook#110]
last time it failed: https://github.com/galaxyproject/tools-devteam/issues/317

**Comment by martenson** [comment]
I tried again, no luck, stuck here:

```
128.118.201.178 - - [02/May/2018:20:11:39 +0000] "GET /admin/manage_tool_dependencies HTTP/1.0" 200 - "https://main-installer.galaxyproject.org/admin" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
galaxy.tools.deps.conda_util DEBUG 2018-05-02 20:12:32,593 Executing command: /cvmfs/main.galaxyproject.org/deps/_conda/bin/conda create -y --override-channels --channel iuc --channel bioconda --channel conda-forge --channel defaults --name mulled-v1-71206c22effe4f02960f526961e99857b4140cdce3da5f9a9e75417fc1a3e405 r-argparse=1.0.1 bioconductor-cummerbund=2.16.0
Fetching package metadata .................
Solving package specifications: .
```

**Comment by jennaj** [comment]
I'll retest and see if fixed

**Comment by natefoo** [comment]
This is due to conda/conda#5536, I've been able to get past the solver hang by temporarily setting the defaults in `~/.condarc` to only the `main` and `free` channels as described in the issue comments. After successfully solving the packages, I've undone the temporary change and the installation is in progress.

**Comment by natefoo** [comment]
I've gotten the dependencies installed, however, uploading the test sqlite database results in a metadata failure:

```
uploaded sqlite file
WARNING:galaxy.datatypes.binary:<galaxy.datatypes.binary.SQlite object at 0x2b88b4944710>, set_meta Exception: database is locked
```

**Comment by natefoo** [comment]
I've gotten the database to load trying it a second time - it may be some kind of NFS issue. However, you can't run the tool because it seems to fail to read the input dataset. Here's what's logged when you 1. load the tool and 2. click Insert Plots:

```pytb
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,859 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'x' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,860 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'x' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,861 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'y' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,862 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'y' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.actions INFO 2018-06-04 14:38:15,864 [p:8313,w:5,m:0] [uWSGIWorker5Core1] Added output datasets to history (21.072 ms)
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,864 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,865 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,866 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'x' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,867 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'x' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,867 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'y' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,868 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'y' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,869 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,870 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,871 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,872 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,874 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,875 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,876 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'x' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,877 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'x' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,878 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'y' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,878 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'y' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,879 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,880 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,882 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,882 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,885 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'x' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,886 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'x' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,887 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'y' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,888 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'y' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,889 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,889 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,890 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'x' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,891 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'x' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,892 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'y' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,892 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'y' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,894 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,895 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,896 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,897 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,898 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,898 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,900 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'x' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,900 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'x' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,901 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'y' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,902 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'y' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,903 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,904 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,905 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
galaxy.tools.parameters.basic DEBUG 2018-06-04 14:38:15,906 [p:8322,w:6,m:0] [uWSGIWorker6Core1] Error determining dynamic options for parameter 'gene_id' in tool 'toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/cummeRbund/2.16.0':
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
NameError: name 'input_database' is not defined
```

**Comment by jmchilton** [comment]
I tried another test on main that doesn't use the dynamic options stuff - and it works fine - so the good news is the dependency issues seem to be resolved! The dynamic options work fine for me locally, so there are problems here - that appear to be differences between how dynamic options are resolved - maybe the difference is the DB, the web server, or the object store.

**Comment by natefoo** [comment]
Could you fetch the metadata of your input file from the DB?

**Comment by jmchilton** [comment]
I'm confused - are you asking if the tool be rewritten to do that or if the dynamic options worked for me on usegalaxy.org? This tool doesn't read options from the metadata - it reads options from the data 😞 - likely this is part of the problem.

**Comment by natefoo** [comment]
No I was asking for the HDA metadata from your local instance to compare. Although maybe it's irrelevant, I guess the issue here is that the dynamic option is being called without the dataset being defined in the param dict?

**Comment by natefoo** [comment]
Ah. Before those, you get:

```pytb
Traceback (most recent call last):
  File "lib/galaxy/tools/parameters/basic.py", line 835, in get_options
    return eval(self.dynamic_options, self.tool.code_namespace, call_other_values)
  File "<string>", line 1, in <module>
  File "/galaxy/main/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/cummerbund/78fcfc04fcfe/cummerbund/cummeRbund_options.py", line 10, in get_samples
    samples = conn.execute( 'SELECT sample_name FROM samples ORDER BY sample_name' )
OperationalError: database is locked
```

**Comment by jmchilton** [comment]
Well that is illustrative - thanks! Want to just move all the user data on usegalaxy.org to a fast, local SSD and close this out?

**Comment by natefoo** [comment]
:unamused:

**Comment by jmchilton** [comment]
https://docs.python.org/3/library/sqlite3.html

> By default, check_same_thread is True and only the creating thread may use the connection. If set False, the returned connection may be shared across multiple threads. When using multiple threads with the same connection writing operations should be serialized by the user to avoid data corruption.

That doesn't seem like the problem but might be worth trying to set that to false when opening sqlite connections - let me see if I can find something more likely to help.

**Comment by jmchilton** [comment]
Ugh - I'm frustrated I can't find a "just assume I'm the only thread in the world and don't lock anything please" mode for sqlite.

We could try:

```
# Open database in autocommit mode by setting isolation_level to None.
conn = sqlite3.connect('app.db', isolation_level=None)

# Set journal mode to WAL.
conn.execute('pragma journal_mode=wal')
```

We could try reading the whole file first before opening the sqlite connection - if it is small keeping it in memory otherwise just hope the read causes everything in NFS to be properly cached ahead of time.

I'm not sure what else... I'm not really sure how to test which of these will work on main in an efficient way.

**Comment by natefoo** [comment]
"Testing fixes on Main in an efficient way" is indeed difficult. I do have a TACC instance of my own that I use for testing, so I could run your branch on that, if I can get it to exhibit the same issue as Main does (this could be a multi-VM issue).

**Comment by natefoo** [comment]
So, in my TACC instance it doesn't display the locked message, but does have the rest of the dynamic option load failures. So I'm not sure if the locked error happens every time on Main or just happened the one time I saw it.

**Comment by natefoo** [comment]
I can't make much sense of the dynamic options code. `input_database` should be in the locals (`call_other_values`) passed to `eval()` but it's not? Except I can't even determine what puts it there. If I knew where that happened I could try to see why it's not happening. Presumably an exception is being silently dropped somewhere? I am not sure how it can be missing when a dataset is selected.

**Comment by davebx** [comment]
@natefoo when galaxy#6302 is merged, I'm going to propose getting the dynamic options from `input_dataset.metadata.genes` and `input_dataset.metadata.samples` instead, thus (thankfully, finally) obviating the need for the garbage code file that hasn't worked in years.
