### ISSUE TITLE
Get Data: EBI SRA is failing for all imports

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#117]
New as of 18.05 pre-release at Galaxy Main https://usegalaxy.org.

Works at Galaxy Europe. And works on Main if the FTP link is pasted into the Upload tool. It is the direct "Galaxy" links that are problematic at Main (fastq or sra data).

**test histories:** 

 - https://usegalaxy.org/u/jen/h/test-ebi-sra-import
 - https://usegalaxy.eu/u/jenj/h/test-ebi-sra-import

**Comment by jennaj** [comment]
@dannon @martenson The error looks very similar to one of the errors get data > ucsc is reporting. https://github.com/galaxyproject/usegalaxy-playbook/issues/119. Didn't notice that before.

```
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 685, in finish_job
    self._finish_or_resubmit_job(job_state, stdout, stderr, exit_code)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 432, in _finish_or_resubmit_job
    job_state.job_wrapper.finish(stdout, stderr, exit_code, check_output_detected_state=check_output_detected_state)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 1288, in finish
    dataset.init_meta(copy_from=dataset)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 2202, in init_meta
    return self.datatype.init_meta(self, copy_from=copy_from)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 2132, in datatype
    return datatype_for_extension(self.extension)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 2042, in datatype_for_extension
    ret = datatypes_registry.get_datatype_by_extension(extension)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/registry.py", line 565, in get_datatype_by_extension
    return self.datatypes_by_extension.get(ext, None)
TypeError: unhashable type: 'list'
```

**Comment by jennaj** [comment]
Same failures

**Comment by jennaj** [comment]
UCSC https://github.com/galaxyproject/usegalaxy-playbook/issues/119
GenomeSpace https://github.com/galaxyproject/usegalaxy-playbook/issues/100
EBI SRA https://github.com/galaxyproject/usegalaxy-playbook/issues/117

**Comment by jennaj** [comment]
EBI SRA fails on their end sometimes (their server is busy). Reruns tend to work. When they do:

 - Pass for fastq data loading, so that works now.

 - Fail for srr data:

```
rm: cannot remove ?working?: Directory not empty
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_source/data_source.py", line 118, in <module>
    __main__()
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_source/data_source.py", line 67, in __main__
    datatypes_registry.load_datatypes(root_dir=job_params['job_config']['GALAXY_ROOT_DIR'], config=job_params['job_config']['GALAXY_DATATYPES_CONF_FILE'])
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/registry.py", line 111, in load_datatypes
    tree = galaxy.util.parse_xml(config)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/util/__init__.py", line 219, in parse_xml
    root = tree.parse(fname, parser=ElementTree.XMLParser(target=DoctypeSafeCallbackTarget()))
  File "/cvmfs/main.galaxyproject.org/python/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: '/cvmfs/main.galaxyproject.org/galaxy/datatypes_conf.xml'
```

**Comment by natefoo** [comment]
The `IOError` is described in galaxyproject/galaxy#6245. There are some things we can do to fix it but it should be infrequent and, if encountered, you should be able to rerun the tool.

For the connection errors, we should consider making the tool retry a few times.

**Comment by jennaj** [comment]
thanks for testing, also worked for me
