### ISSUE TITLE
Get Data: UCSC Main reporting metadata problems with all imports

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#119]
**End User workaround:** Click on the link to "autodetect" the dataset's metadata.

**Test history:** https://usegalaxy.org/u/jen/h/test-history-get-data-ucsc-main

**Problem:** Metadata assignment for imported datasets. BED/GFT produce this. Fasta output (_protein_, from MAF) is being detected as BED (not FASTA). See datasets 5-7-8. Dataset 6 failed -- probably a query problem or UCSC timed out -- rerun in dataset 10 (also failed) -- dataset 9 is the same query, but uses a different source table -- this is "probably" a UCSC problem but will retest when other metadata issues are resolved.

**Screenshots**

Initial after loading from UCSC:

<img width="251" alt="screen shot 2018-05-08 at 8 21 24 am" src="https://user-images.githubusercontent.com/8999735/39766355-f0cf0402-5298-11e8-993d-acb203841816.png">

After using "autodetect"

<img width="253" alt="screen shot 2018-05-08 at 8 23 15 am" src="https://user-images.githubusercontent.com/8999735/39766427-1db0f138-5299-11e8-9dd5-e3c733a18732.png">

**Comment by jennaj** [comment]
Not all file types produce a metadata error, some will fail outright. These seem to be related to tabular output that is not GTF, BED, etc. Tests in same history above. 

**UCSC Archaea** has the same issues, also in same test history.

**Example output selected from UCSC TB:** All fields from the selected table

**Example error:** 

```
Job Traceback
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 685, in finish_job
    self._finish_or_resubmit_job(job_state, stdout, stderr, exit_code)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 432, in _finish_or_resubmit_job
    job_state.job_wrapper.finish(stdout, stderr, exit_code, check_output_detected_state=check_output_detected_state)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 1288, in finish
    dataset.init_meta(copy_from=dataset)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 2202, in init_meta
    return self.datatype.init_meta(self, copy_from=copy_from)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 2132, in datatype
    return datatype_for_extension(self.extension)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/model/__init__.py", line 2042, in datatype_for_extension
    ret = datatypes_registry.get_datatype_by_extension(extension)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/registry.py", line 565, in get_datatype_by_extension
    return self.datatypes_by_extension.get(ext, None)
TypeError: unhashable type: 'list'
```

**Comment by jennaj** [comment]
Still fails after update this morning.

Haven't been able to get an 18.05 pre-release going with all defaults, no conda, and basic git pull/run.sh, so can't test there. @martenson what was your result in a local? I missed that result.

**Comment by jennaj** [comment]
UCSC https://github.com/galaxyproject/usegalaxy-playbook/issues/119
GenomeSpace https://github.com/galaxyproject/usegalaxy-playbook/issues/100
EBI SRA https://github.com/galaxyproject/usegalaxy-playbook/issues/117

PR fix https://github.com/galaxyproject/galaxy/pull/6196

**Comment by jennaj** [comment]
Both UCSC Main/Archaea work now for all output types (except for "Custom track", but that never worked and probably shouldn't be sent to Galaxy, is intended for other use cases. Just noting it here in case a user runs into it.

```WARNING:galaxy.model:Datatype class not found for extension 'customTrack'```

Thanks everyone for the fix!
