### ISSUE TITLE
MAF tools errors: header only "green" empty datasets + python failures for simple queries

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#130]
ping @blankenberg @natefoo 

**test history**: https://usegalaxy.org/u/jen/h/test-maf-tools---tool-group-fetch-alignmentssequences

Only retested two tools. The Join problem was reported to galaxy-bugs. Found the other while testing. Other MAF tools likely impacted.

----

**tool 1:** Join MAF blocks by Species (Galaxy Version 1.0.0)

Test datasets 42-47. Works with <=15 species fails with 20. Green "success" result dataset with only a header returned. Used an imported MAF (single chromosome, chrY UCSC, intact, 475,040 blocks, dataset 32).

This should be a tool failure (red) or at least report in the comments/stderr/stdout that the job ran out of memory at some point (if memory is the real issue). Job info stdout just lists the species, stderr no content. If there is an upper limit on species, it would be good to note that in the tool help next revision.

Test dataset 48. Selected all species using a smaller MAF (single chromosome, chrM UCSC, intact, 460 blocks, dataset 21). This was successful and has proper content. 

----

**tool 2:** Extract MAF blocks given a set of genomic intervals (Galaxy Version 1.0.1)

Test datasets 34-41. Fails when given a single genomic interval and just 2 species selected. Red error dataset with a python error. Used the natively indexed 100-way (hg19).

Test dataset 49. Selected all species using a smaller MAF (single chromosome, chrM UCSC, intact, 460 blocks, dataset 21) AND an interval/bed input that didn't actually contain any intervals (dataset 23).

Same error results for both very different tests.

```
stderr
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/maf/interval2maf.py", line 145, in <module>
    __main__()
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/maf/interval2maf.py", line 112, in __main__
    for num_regions, region in enumerate(bx.intervals.io.NiceReaderWrapper(open(interval_file, 'r'), chrom_col=chromCol, start_col=startCol, end_col=endCol, strand_col=strandCol, fix_strand=True, return_header=False, return_comments=False)):
  File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/site-packages/six.py", line 564, in next
    return type(self).__next__(self)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/site-packages/bx/intervals/io.py", line 190, in __next__
    nextitem = GenomicIntervalReader.next( self )
  File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/site-packages/six.py", line 564, in next
    return type(self).__next__(self)

... much more of the same, repeating ...

  File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/site-packages/six.py", line 564, in next
    return type(self).__next__(self)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/site-packages/bx/intervals/io.py", line 190, in __next__
    nextitem = GenomicIntervalReader.next( self )
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by jennaj** [comment]
python issue fixed with https://github.com/galaxyproject/galaxy/pull/9393

but now the indexed hg19 46way and 100way are not found? Creating a distinct issue ticket.
