### ISSUE TITLE
Update HISAT2 once in MTS (dbkey assignment fix)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#132]
PR: HISAT2 properly set dbkey on outputs https://github.com/galaxyproject/tools-iuc/pull/1902

usegalaxy-playbook/issue: Mappers label BAM output with fastq dbkey, not aligned genome dbkey. Or do not assign it at all when fastq does not have dbkey assigned. https://github.com/galaxyproject/usegalaxy-playbook/issues/104

**Comment by jennaj** [comment]
Also address this PR: HISAT2 2.1.0 fails when options under "Scoring options" used https://github.com/galaxyproject/tools-iuc/issues/1792

**Comment by natefoo** [comment]
It's in the MTS, that's an automated process on merge on tools-iuc now (I believe for all repos?).

**Comment by natefoo** [comment]
Good news: I updated HISAT2 to `6ab42baa56e9` on both Test and Main. On Test, which did not have the latest version, I used ephemeris!

Bad news: On Main, which had an older revision of the latest version, ephemeris claimed to update, but didn't. So I had to do this one via the web UI. =(

```console
$ cat hisat-upgrade.yml
---
api_key: deadbeef
install_tool_dependencies: false
install_resolver_dependencies: true
tools:
- name: hisat2
  owner: iuc
  tool_panel_section_id: ngs-rna-tools
$ shed-tools install -v -g https://main-installer.galaxyproject.org/ -t hisat-upgrade.yaml
(1/1) Installing repository hisat2 from iuc to section "ngs-rna-tools" at revision 6ab42baa56e9 (TRT: 0:00:02.660426)
	Repository hisat2 is already installed.
	repository hisat2 installed successfully (in 0:00:03.432022) at revision 6ab42baa56e9
Installed repositories (1): [('hisat2', None)]
Skipped repositories (0): []
Errored repositories (0): []
All repositories have been processed.
Total run time: 0:00:06.092810
```

Also, when installing on Test, it timed out and, when attempting to increase the timeout, it failed (tool installation succeeded anyway):

```pytb
Timeout during install of hisat2, extending wait to 1h
Traceback (most recent call last):
  File "/home/nate/.virtualenvs/ephemeris/bin/shed-tools", line 11, in <module>
    sys.exit(main())
  File "/home/nate/.virtualenvs/ephemeris/local/lib/python2.7/site-packages/ephemeris/shed_tools.py", line 744, in main
    install_tool_manager.install_repositories()
  File "/home/nate/.virtualenvs/ephemeris/local/lib/python2.7/site-packages/ephemeris/shed_tools.py", line 621, in install_repositories
    success = wait_for_install(repository=repository, tool_shed_client=self.tsc, timeout=3600)
  File "/home/nate/.virtualenvs/ephemeris/local/lib/python2.7/site-packages/ephemeris/shed_tools.py", line 454, in wait_for_install
    finished = install_done(repository, tool_shed_client)
  File "/home/nate/.virtualenvs/ephemeris/local/lib/python2.7/site-packages/ephemeris/shed_tools.py", line 447, in install_done
    installed_repo_list = tool_shed_client.get_repositories()
  File "/home/nate/.virtualenvs/ephemeris/local/lib/python2.7/site-packages/bioblend/galaxy/toolshed/__init__.py", line 36, in get_repositories
    return self._get()
  File "/home/nate/.virtualenvs/ephemeris/local/lib/python2.7/site-packages/bioblend/galaxy/client.py", line 128, in _get
    status_code=r.status_code)
bioblend.ConnectionError: GET: error 502: '<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.12.2</center>\r\n</body>\r\n</html>\r\n', 0 attempts left: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.12.2</center>
</body>
</html>
```

**Comment by jennaj** [comment]
Fixed & closing. Just Bowtie2 and RNA STAR need a fix now. Other mappers Ok, see https://github.com/galaxyproject/usegalaxy-playbook/issues/104#issuecomment-395083588
