### ISSUE TITLE
Cufflinks 2.2.1.0 is reporting a missing dependency

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#146]
**Workaround**: Please consider using the updated tools/workflows for RNA-seq covered in the Galaxy tutorials (and avoid this tool): https://galaxyproject.org/learn/

----

Details:

First reported on 6/21/18 through both galaxy-bugs and galaxy biostars.

stderr

```
Traceback (most recent call last):
  File "/jetstream/scratch0/main/jobs/19877546/tool_files/cufflinks_wrapper.py", line 9, in <module>
    from galaxy.datatypes.util.gff_util import parse_gff_attributes, gff_attributes_to_str
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/util/gff_util.py", line 6, in <module>
    from bx.intervals.io import GenomicInterval, GenomicIntervalReader, MissingFieldError, NiceReaderWrapper, ParseError
ImportError: No module named bx.intervals.io
```

ping @natefoo

**Comment by jennaj** [comment]
The tool has been corrected. Be sure to use the most current version on the server when using Galaxy Main https://usegalaxy.org

 -  **Cufflinks transcript assembly and FPKM (RPKM) estimates for RNA-Seq data (Galaxy Version 2.2.1.2)**
