### ISSUE TITLE
MAF tools do not find indexed hg19 46-way or 100-way. CVMFS path problem?

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#290]
Found while retesting this fix: https://github.com/galaxyproject/usegalaxy-playbook/issues/130#issuecomment-595373150

**Test history:** https://usegalaxy.org/u/jen/h/test-maf-tools---tool-group-fetch-alignmentssequences

dataset 51: `Fatal Error: The MAF source specified (46_WAY_MULTIZ_hg19) appears to be invalid.`
dataset 50: `Fatal Error: The MAF source specified (100_WAY_MULTIZ_v2_hg19) appears to be invalid.`

@natefoo @davebx  - Paths in CVMFS changed. Maybe these were missed when others fixed?

**Comment by jennaj** [comment]
Related issues: https://github.com/search?q=org%3Agalaxyproject+maf&type=Issues

Many involve MAF tools, not just data. Some might be resolved, needs an update.

**Comment by natefoo** [comment]
My favorite construct: [catch exceptions and silently ignore them](https://github.com/galaxyproject/galaxy/blob/d7921ae4dda5388dfda1f346a6a3b5ca7436a9ee/lib/galaxy/datatypes/util/maf_utilities.py#L300).

```pytb
Traceback (most recent call last):
  File "/home/ndc/maf_utilities.py", line 299, in maf_index_by_uid
    return bx.align.maf.MultiIndexed(maf_files, keep_open=True, parse_e_rows=False)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/bx/interval_index_file.py", line 175, in __init__
    for fname in filenames]
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/bx/interval_index_file.py", line 175, in <listcomp>
    for fname in filenames]
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/bx/interval_index_file.py", line 178, in new_indexed_access
    return self.indexed_access_class(data_filename, index_filename, keep_open, **kwargs)
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/bx/interval_index_file.py", line 234, in __init__
    self.f = self.open_data()
  File "/cvmfs/main.galaxyproject.org/venv/lib/python3.6/site-packages/bx/align/maf.py", line 47, in open_data
    return TextIOWrapper(data, encoding="ascii")
AttributeError: 'SeekableLzopFile' object has no attribute 'readable'
```

I think [SeekableLzopFile](https://github.com/bxlab/bx-python/blob/master/lib/bx/misc/seeklzop.py) needs to implement [io.IOBase](https://docs.python.org/3/library/io.html#io.IOBase)?

**Comment by mvdbeek** [comment]
Combined with lack of testing it's a thing of beauty!

**Comment by jennaj** [comment]
Any chance we could get this to work? We also need to open up the Pairwise tool from this suite to accept inputs from the history (there might be a ticket for this already somewhere). That said, I think new tools are coming. Updates or crosslinks would be appreciated. 

Current forum topic about this -> https://help.galaxyproject.org/t/extract-pairwise-maf-blocks/13698/
