### ISSUE TITLE
On usegalaxy.org, some tools fail if a history has a 'training' tag

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/usegalaxy-playbook#361]
**Describe the bug**
For histories with the 'training' tag, uploading a file from a url fails with the following error:

```
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/data_fetch.py", line 17, in <module>
    import bdbag.bdbag_api
ModuleNotFoundError: No module named 'bdbag'
```

I've shared the history here https://usegalaxy.org/u/cat-bro/h/datafetch-history.  The first upload succeeds and the second fails because training tag has been added.  I can't think of any other variables that could be affecting it.

**Comment by cat-bro** [comment]
I can no longer reproduce this.  Data fetch works for histories with the `training` tag.  Thanks Galaxy Main!

**Comment by cat-bro** [comment]
Reopening this issue because there is another tool failing with the 'training' tag on the history, working otherwise.

tool id: `ucsc_table_direct1 `
stderr:
```
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_source/data_source.py", line 16, in <module>
    from galaxy.datatypes import sniff
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/sniff.py", line 25, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```
