### ISSUE TITLE
Unicycler failing immediately with paired-end collection input

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#82]
Create assemblies with Unicycler (Galaxy Version 0.4.1)

Test history with failure: https://usegalaxy.org/u/jen/h/test-history-unicycler---collection-input

Not sure if just a problem with tool execution at Galaxy Main/PCS Bridges or a tool wrapper problem.

ping @natefoo

**Comment by natefoo** [comment]
The error is:

```pytb
 Traceback (most recent call last):
   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/pulsar.py", line 342, in __prepare_job
     job_wrapper.prepare(**prepare_kwds)
   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 858, in prepare
     self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 447, in build
     raise e
 KeyError: 'is_of_type'
```

I believe this is fixed in version 0.4.1.1 (at least, it seems to work for me using your test history).
