### ISSUE TITLE
SnpEff version 4.0.0 and 4.1.0 fail at main. Version 4.3k.0 (latest) works.

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/usegalaxy-playbook#98]
Test history: https://usegalaxy.org/u/jen/h/snpeff-database-download-test-history

Retest tracking in: https://github.com/galaxyproject/usegalaxy-playbook/issues/86

Known problem with 4.1.0 and 4.3k.0: https://github.com/galaxyproject/tools-iuc/issues/1354

Error example (see history for details):

```
Dataset Error
An error occured while running the tool toolshed.g2.bx.psu.edu/repos/iuc/snpeff/snpEff_download/4.1.0.

Tool execution generated the following messages:

Fatal error: Exit code 255 (Error)
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/galaxy-repl/main/jobdir/018/587/18587256/_job_tmp -Xmx7g -Xms256m
00:00:00	SnpEff version SnpEff 4.1l (build 2015-10-03), by Pablo Cingolani
00:00:00	Command: 'download'
00:00:00	Reading configuration file '/cvmfs/main.galaxyproject.org/deps/_conda/envs/__snpEff@4.1/share/snpeff-4.1l-4/snpEff.config'. Genome: 'Bdellovibrio_bacteriovorus_str_tiberius'
00:00:00	Reading config file: /cvmfs/main.galaxyproject.org/deps/_conda/pkgs/snpeff-4.1l-4/share/snpeff-4.1l-4/snpEff.config
java.lang.RuntimeException: Property: 'Bdellovibrio_bacteriovorus_str_tiberius.genome' not found
	at ca.mcgill.mcb.pcingola.interval.Genome.<init>(Genome.java:102)
	at ca.mcgill.mcb.pcingola.snpEffect.Config.readGenomeConfig(Config.java:594)
	at ca.mcgill.mcb.pcingola.snpEffect.Config.readConfig(Config.java:562)
	at ca.mcgill.mcb.pcingola.snpEffect.Config.init(Config.java:422)
	at ca.mcgill.mcb.pcingola.snpEffect.Config.<init>(Config.java:107)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.loadConfig(SnpEff.java:265)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:79)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:71)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:883)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:128)
00:00:00	Logging
```

ping @natefoo @davebx

**Comment by jennaj** [comment]
Tool is being updated, let's not worry about the older versions. Closing. https://github.com/galaxyproject/tools-iuc/pull/1787
